language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-lxc
  - sudo apt-get install -y libyaml-dev
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install .
script: locker --help