type:           map
matching-rule:  "any"
mapping:
    #"network":
    "defaults":
        type:           map
        mapping:
            "cgroup":
                type:       seq
                sequence:
                    - type:     str
            "dns":
                type:       seq
                sequence:
                    - type:     str
    "containers":
        type:           map
        matching-rule:  "any"
        mapping:
            re;(^[a-zA-Z][a-zA-Z\d]*$):
                type:   map
                mapping:
                    "template":
                        type:   map
                        matching-rule:  "any"
                        mapping:
                            "name":
                                type:       str
                                required:   true
                            re;(^.+$):
                                type:       str
                    "clone":
                        type:       str
                    "download":
                        type:   map
                        matching-rule:  "any"
                        mapping:
                            "dist":
                                type:       str
                                required:   true
                            "release":
                                type:       str
                                required:   true
                            "arch":
                                type:       str
                                required:   true
                            re;(^.+$):
                                type:       str
                    "links":
                        type:       seq
                        sequence:
                            - type:     str
                    "ports":
                        type:       seq
                        sequence:
                            - type:     str
                    "volumes":
                        type:       seq
                        sequence:
                            - type:     str
                    "fqdn":
                        type:       str
                    "cgroup":
                        type:       seq
                        sequence:
                            - type:     str
                    "dns":
                        type:       seq
                        sequence:
                            - type:     str
